language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.6'
  - 'nightly'

cache:
  directories:
    - "$HOME/.pip-cache/"

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install --egg -r requirements.txt --cache-dir $HOME/.pip-cache

script:
  behave features/