language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.6.1'
  - 'nightly'

cache: pip

addons:
  firefox: latest

before_install:
  - sudo apt-add-repository ppa:yandex-qatools/allure-framework -y
  - sudo apt-get -qq update
  - sudo apt-get install allure-commandline -y
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver


install:
  - pip install codecov
  - pip install allure-behave
  - pip install -r requirements.txt

script:
  - coverage run --source='.' -m behave -f allure_behave.formatter:AllureFormatter -o report features/
  - ls 

after_script:
  - codecov
  - allure --version
  - ls
  - allure serve report
