language: python

python:
  - '3.3'

cache: pip

addons:
  firefox: latest
  
before_install:
  - sudo apt-get install oracle-java9-set-default
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - wget -O allure-2.3.tgz https://bintray.com/qameta/generic/download_file?file_path=io/qameta/allure/allure/2.3/allure-2.3.tgz
  - mkdir allure
  - tar -xzf allure-2.3.tgz -C allure
  - ls
  - cd ./allure/allure-2.3/bin
  - ls
  - cd ../../..
  - export PATH=$PATH:$PWD/allure/allure-2.3/bin/allure
  


install:
  - pip install codecov
  - pip install allure-behave
  - pip install -r requirements.txt

script:
  - coverage run --source='.' -m behave -f allure_behave.formatter:AllureFormatter -o report features/
  - ls 

after_script:
  - codecov
  - java -version
  - ./allure/allure-2.3/bin/allure --version
  - ls
  - ./allure/allure-2.3/bin/allure serve report
  
